const mascotas = [
  {
    nombre: "Guapísimo",
    html: "guapisimo",
    sexo: "macho",
    edad: "cachorro",
    peso: "ligero",
    tamaño: "pequeño",
    pelo: "corto",
    actividad: "media",
    imagen: "guapisimo.jpg",
  },
  {
    nombre: "Piraña",
    html: "pirana",
    sexo: "hembra",
    edad: "adulto",
    peso: "ligero",
    tamaño: "pequeño",
    pelo: "largo",
    actividad: "alta",
    imagen: "piraña.jpg",
  },
  {
    nombre: "Toribio",
    html: "toribio",
    sexo: "macho",
    edad: "adulto",
    peso: "pesado",
    tamaño: "grande",
    pelo: "largo",
    actividad: "baja",
    imagen: "toribio.jpg",
  },
  {
    nombre: "Luna",
    html: "luna",
    sexo: "hembra",
    edad: "cachorro",
    peso: "mediano",
    tamaño: "mediano",
    pelo: "corto",
    actividad: "media",
    imagen: "luna.png",
  },
];
